name: Broken Link Checker

on:
  schedule:
    # Run at 5:00 AM on Monday and Friday
    - cron: '0 5 * * 1,5'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    name: Check for broken and insecure links
    
    # Need permissions to create issues
    permissions:
      contents: read
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Download previous cache
        uses: dawidd6/action-download-artifact@v2
        with:
          name: link-check-cache
          path: .
          if_no_artifact_found: warn
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests markdown beautifulsoup4 PyGithub

      - name: Check links
        env:
          CHECKER_TOKEN: ${{ secrets.CHECKER_TOKEN }}
        run: python ./.github/scripts/link_checker.py
        
      - name: Upload cache file
        uses: actions/upload-artifact@v3
        with:
          name: link-check-cache
          path: .link_check_cache.json
          retention-days: 90
